### PR TITLE
Feature: Definition types

### LINKED ISSUE #18: Request: Add ts definitions

### PR DESCRIPTION
**Pull request by piotr-cz**
Fixes #18

### CODE REVIEW

**Comment by piotr-cz** [comment]
Testing instructions:

```console
npm uninstall react-number-easing
npm install "github:piotr-cz/react-number-easing#feature/definition-types"
```

**Comment by piotr-cz** [comment]
I didn't success with referencing types from the `@types/eases` - it didn't show easing types in VSCode when using this package in another project so I hardcoded them.

**Comment by namosuke** [comment]
@javierbyte @adjohu @migreva 
I love this project and I really want to use this on my TypeScript application. Is there any progress about adding types?

**Comment by javierbyte** [comment]
amazing thank you! a bit late in my reply

**Comment by piotr-cz** [comment]
@javierbyte 
What about releasing new version?

**Pull request merged**
